json.questions_count @user.questions.count 
json.answered_solutions_count @user.answered_solutions.count
json.image_url @user.user_profile.image_url
json.curio_points  @user.points
json.high_fives @user.user_profile.votes_for.count
json.location @user.user_profile.location
json.full_name @user.full_name
json.phone_number @user.phone_number
json.id @user.id