development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: reechAlpha_dev
  pool: 5
  username: root
  password: r33ch!
  socket: /var/run/mysqld/mysqld.sock
test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: reechAlpha_test
  pool: 5
  username: root
  password: r33ch!
  socket: /var/run/mysqld/mysqld.sock
production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: reechAlpha_production
  pool: 5
  username: root
  password: r33ch!
  socket: /var/run/mysqld/mysqld.sock