development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: reechAlpha_dev1
  pool: 5
  username: root
  password: root123
  socket: /var/run/mysqld/mysqld.sock
test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: reechAlpha_test
  pool: 5
  username: root
  password: root123
  socket: /var/run/mysqld/mysqld.sock
production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: reechAlpha_dev1
  pool: 5
  username: root
  password: root123
  socket: /var/run/mysqld/mysqld.sock