development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: reechAlpha_development
  port: 3306
  pool: 5
  username: root
  password: 
  socket: /var/run/mysqld/mysqld.sock
test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: reechAlpha_test
  port: 3306
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock
production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: reechAlpha_production
  port: 3306
  pool: 5
  username: root
  password: 
  socket: /var/run/mysqld/mysqld.sock
