development:
  mem_limit: 128M
  morphology: stem_en
  enable_star: true
  min_infix_len: 3

test:
  mem_limit: 128M
  morphology: stem_en
  enable_star: true
  min_infix_len: 3

production:
  mem_limit: 128M
  morphology: stem_en
  enable_star: true
  min_infix_len: 3
