development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: middlmen4_dev
  pool: 5
  username: root
  password: pazzword
  socket: /var/run/mysqld/mysqld.sock
test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: middlmen4_test
  pool: 5
  username: root
  password: pazzword
  socket: /var/run/mysqld/mysqld.sock
production:
  adapter: mysql2
  encoding: utf8
  database: middlmen4_prod
  pool: 5
  username: root
  password: pazzword
  socket: /var/run/mysqld/mysqld.sock
